version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: maroc-ship
      # So you don't have to use root, but you can if you like
      MYSQL_USER: root
      # You can use whatever password you like
      MYSQL_PASSWORD: root
      # Password for root access
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3309:3306
      - 3309:3306
    volumes:
      - marocShip:/var/lib/mysql

  dockerPhpMyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    links:
      - mysql
    restart: always
    ports:
      - 8081:80

  dockerJboss:
    image: quay.io/wildfly/wildfly
    ports:
      - 8085:8080
    volumes:
      - ./target/maroc_ship-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war


# Names our volume
volumes:
 marocShip: